### ISSUE TITLE
Add fields when user Sign Up

### ISSUE THREAD

**Issue by Gakamine** [graphql-devise/graphql_devise#28] opened 2019-10-21 10:05 UTC
Hello !
I have setup graphql_devise on my server. Everything is working but I wish I could add fields when the user sign up. For example, I wish to add a field named "username" when I'm adding a new user with the mutation "userSignUp".
How can I do that ?
Thank you.

**Comment by 00dav00** [comment] 2019-10-21 13:00
Hi @Gakamine, in the dummy app `signUp` mutation the field `name` [was added](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/graphql/mutations/sign_up.rb#L3). Basically what you need to do is:
- create a mutation that inherits from `GraphqlDevise::Mutations::SignUp` 
- define you custom response type, in this case `Types::UserType`.
- tell gql_devise which `signUp` mutation to use in the [routes file](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/config/routes.rb#L4)

Is this what you were looking for?

**Comment by Gakamine** [comment] 2019-10-22 02:46
Thank you !! @00dav00 @mcelicalderon 
I think it would be a good idea to add an option in the mount method, it would be easier for small changes. I would still use the solution that @00dav00 gave me because I don't like either that my route file know too much about the model and I want to add multiple field, it would make my route file impossible to read.

**Comment by aarona** [comment] 2019-10-23 01:27
I haven't fully customized my own mutations yet since I'm still attempting a simple `create-react-app` example so I haven't hit this road block yet but I imagine being able to have your `SignUp` mutation  inherit from `GraphqlDevise::Mutations::SignUp` and add whatever fields you wanted (First Name, Last Name, Phone Number etc) and just reference that mutation in your routes config.

I agree with @Gakamine that any custom fields you want for your custom mutations should be in that file and that simply doing:

```
operations: {
  signIn: Mutations::MySignIn # this mutation will have fields added to it for what you need
}
```

**Comment by mcelicalderon** [comment] 2019-10-30 03:34
Reopening this so I don't forget to implement

**Comment by aarona** [comment] 2019-11-25 04:52
You may want to support nested attributes also @mcelicalderon. Devise supports it, so it should be assumed that we would also. See: https://github.com/plataformatec/devise#strong-parameters

**Comment by lassiter** [comment] 2020-07-05 23:06
> Hi @Gakamine, in the dummy app `signUp` mutation the field `name` [was added](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/graphql/mutations/sign_up.rb#L3). Basically what you need to do is:
> 
> * create a mutation that inherits from `GraphqlDevise::Mutations::SignUp`
> * define you custom response type, in this case `Types::UserType`.
> * tell gql_devise which `signUp` mutation to use in the [routes file](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/config/routes.rb#L4)
> 
> Is this what you were looking for?

@00dav00 I tried your example with the dummy app but it errored out ` undefined method 'resource_class' for nil:NilClass `

```
# frozen_string_literal: true

module Mutations
  class SignUp < GraphqlDevise::Mutations::SignUp
    field :user, Types::UserType, null: true
    field :profile, Types::ProfileType, null: true

    def resolve(email:, **attrs)
      binding.pry
      original_payload = super
      original_payload.merge(user: original_payload[:authenticatable])
    end
  end
end
```

This is my code, I planned on adding to it to create a profile.

**Comment by mcelicalderon** [comment] 2020-07-06 02:21
Hey @lassiter! So, not sure what the profile field is, but you should definitively include another key in the hash returned by the resolver method. This issue is related to adding more values to the user model when using the sign up mutation, so not sure if you are trying to do this. If that's the case, just like in [here](https://github.com/graphql-devise/graphql_devise/blob/master/spec/dummy/app/graphql/mutations/sign_up.rb#L5), what you need to add is an argument to your mutation. Anyway,  the undefined method error seems weird to me, please send the backtrace so we can identify the problem.

**Comment by mcelicalderon** [comment] 2020-07-06 15:15
Closing this one as the more we work en the gem, the less I think we will end up implementing this as the cleaner alternative is to have your own mutation inherit from the one on the gem with the additional arguments.

**Closed by mcelicalderon** 2020-07-06 15:15 UTC
Labels: enhancement

**Comment by keithmgould** [comment] 2021-01-15 13:05
Might have missed it, but I spent a while looking for this in README before coming here. I think someone else mentioned also but might be nice to have this in readme. happy to make a PR to place in README if that helps.

**Comment by keithmgould** [comment] 2021-01-15 13:42
Actually noticing an issue with the above subclass solution.

I only use a single endpoint, so I have the mounting operations in my own schema. This works great. 

However, if I try to do the above solution, the rest of my schema is not seen by graphiql.

So:

```
  mount_graphql_devise_for 'User', at: '/graphql', operations: {
    sign_up: Mutations::Users::SignUp
  }

  post "/graphql", to: "graphql#execute"
  get "/graphql", to: "graphql#execute"
```

...causes all of my other schema to be ignored. 

I really want to keep a single endpoint. Is it possible?

**Comment by 00dav00** [comment] 2021-01-15 13:58
Hi @keithmgould, if you mount the operations using the routes, the gem expects the endpoint to be exclusively for auth. If want to use a single endpoint/schema you will have to use the schema plugin, have you checked this [section of the readme](https://github.com/graphql-devise/graphql_devise#mounting-operations-into-your-own-schema)?
Please take a look at the steps there as well as the example in the tests and let us know if it works for you, if something is not working correctly I would recommend opening a different issue to keep track of the problem :)

**Comment by keithmgould** [comment] 2021-01-15 14:07
Hi @00dav00, happy to open a different thread, though the issue is v similar: it is adding a new field to SignUp, though in my case I want a single endpoint. I have successfully followed instructions you linked to, have auth and my own schema in the same graph (yay!) however now that I want to add a new field to the sign-up mutation, I don't know what to do. The solution above does not work for reasons mentioned.

**Comment by 00dav00** [comment] 2021-01-15 14:14
Let's open a new issue @keithmgould. It would be helpful if you can post:
- The schema
- The inherited type 
- The controller were the schema is added
- The error you are getting

And just to confirm, you need to remove the route if you want to have the auth operations in the same schema.
