### ISSUE TITLE
mutation': Second definition of 'mutation(...)' (GraphqlDevise::Types::MutationType) is invalid

### ISSUE THREAD

**Issue by Gakamine** [graphql-devise/graphql_devise#59] opened 2020-01-24 15:46 UTC
Hello,

I have updated the gem to the 0.9.1 and since I can't start my application on production server.
I have the following errors: https://pastebin.com/7U9Y2V6e
Do you have any idea of what could be blocking ?
Thank you !

**Comment by WoodburyShortridge** [comment] 2020-01-24 18:31
Having save issue on production only:

`! Unable to load application: GraphQL::Error: Second definition of `mutation(...)` (GraphqlDevise::Types::MutationType) is invalid, already configured with GraphqlDevise::Types::MutationType`

@
```
graphql (1.9.18)
    graphql_devise (0.9.1)
      devise_token_auth (>= 0.1.43)
      graphql (>= 1.8)
      rails (>= 4.2)
```

@Gakamine any luck?

**Comment by 00dav00** [comment] 2020-01-24 19:09
Hey @Gakamine, I'm not fully sure this is related, but I saw your stack trace shows you are using the new version of gql-ruby (1.10.0)
```
2020-01-24T15:40:30.532141+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/graphql-1.10.0/lib/graphql/schema.rb:969:in 'mutation': Second definition of 'mutation(...)' (GraphqlDevise::Types::MutationType) is invalid, already configured with GraphqlDevise::Types::MutationType (GraphQL::Error)
```
I think [this](https://github.com/rmosolgo/graphql-ruby/pull/2363) change merged into master with this version could be related.

Was this happening before in prod? 
Could you using fixing the version of gql-ruby to v1.9.1.7 (since it seems like v1.9.1.8 is failing for @WoodburyShortridge ) and let us now if that makes the error go away?

**Comment by WoodburyShortridge** [comment] 2020-01-24 19:24
@00dav00 Looks like you are right, downgrading to gql 1.9.1.7 worked. Should the issue move to graphql-ruby?

**Comment by 00dav00** [comment] 2020-01-24 21:03
@WoodburyShortridge glad to know it worked! Thanks for letting us know.

I think it could be related to gql-ruby, but before moving the prob upstream, do you think you can share your `routes` file (or the relevant part of it) here? 
I think that could be another place where the problem is located.

**Comment by WoodburyShortridge** [comment] 2020-01-24 21:06
sure @00dav00 
```
Rails.application.routes.draw do
  #if Rails.env.development?
  #end
  mount_graphql_devise_for 'User', at: 'auth',operations: { sign_up: Mutations::CreateUser}
  mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  post "/graphql", to: "graphql#execute"
end
```

**Comment by Gakamine** [comment] 2020-01-24 21:07
Fixed by downgrading gql-ruby ! :)

**Comment by mcelicalderon** [comment] 2020-01-25 01:11
Reopening this one as we need to update this gem not to support the new version of gql Ruby, or fix it so it does.

**Comment by WoodburyShortridge** [comment] 2020-01-25 13:42
@mcelicalderon agreed. Thanks.

**Closed** 2020-02-02 16:27 UTC
Labels: bug

**Comment by nitinrajkumar451** [comment] 2022-12-19 08:46
I received this same error when the type in the resolver [BookType!] changed it to [BookType] and it is sorted.

**Comment by lhguerra** [comment] 2023-03-02 19:06
In my case this error was a side-effect, I rolled the server logs way up the hill and found a syntax error in one of my resolvers

**Comment by Zev18** [comment] 2025-03-12 20:41
Restarting the docker container did the trick for me.
