### ISSUE TITLE
Error on rails s: uninitialized constant DeviseTokenAuth::Concerns::TokensSerialization (NameError)

### ISSUE THREAD

**Issue by namolnad** [graphql-devise/graphql_devise#129] opened 2020-08-24 16:09 UTC
### Describe the bug
Getting uninitialized constant error upon starting up rails server
```/Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/active_record_support.rb:7:in `block in <module:ActiveRecordSupport>': uninitialized constant DeviseTokenAuth::Concerns::TokensSerialization (NameError)```

### Environment
[Gemfile](https://gist.github.com/namolnad/fd2ae5fde6ffe540a322d877da02c706)
[Gemfile.lock](https://gist.github.com/namolnad/37232bc5bdb9b10fb84a3404c38db325)

### Steps to reproduce
1. Run `rails s`
1. See uninitialized constant error

### Expected behavior
Expected the server to be able to start as normal

### Actual behavior
<summary>
Stacktrace
<details>
Traceback (most recent call last):
	112: from bin/rails:3:in `<main>'
	111: from bin/rails:3:in `load'
	110: from /Users/danloman/Code/citizenwe-backend/bin/spring:15:in `<top (required)>'
	109: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	108: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	107: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	106: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	105: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	104: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	103: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	102: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	101: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	100: from /Users/danloman/Code/citizenwe-backend/bin/rails:9:in `<top (required)>'
	 99: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
	 98: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 97: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
	 96: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 95: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 94: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 93: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 92: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 91: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
	 90: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
	 89: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
	 88: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	 87: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 86: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	 85: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
	 84: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
	 83: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	 82: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:37:in `start'
	 81: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	 80: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	 79: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	 78: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	 77: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	 76: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	 75: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	 74: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	 73: from config.ru:3:in `block in <main>'
	 72: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	 71: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
	 70: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	 69: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
	 68: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
	 67: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 66: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 65: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 64: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 63: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 62: from /Users/danloman/Code/citizenwe-backend/config/environment.rb:6:in `<main>'
	 61: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application.rb:363:in `initialize!'
	 60: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:60:in `run_initializers'
	 59: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	 58: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	 57: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	 56: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
	 55: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
	 54: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 53: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 52: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 51: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	 50: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	 49: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `run'
	 48: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	 47: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
	 46: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:10:in `execute'
	 45: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/file_update_checker.rb:83:in `execute'
	 44: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:29:in `block in updater'
	 43: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:20:in `reload!'
	 42: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	 41: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:40:in `each'
	 40: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	 39: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	 38: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	 37: from /Users/danloman/Code/citizenwe-backend/config/routes.rb:2:in `<main>'
	 36: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:408:in `draw'
	 35: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
	 34: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
	 33: from /Users/danloman/Code/citizenwe-backend/config/routes.rb:4:in `block in <main>'
	 32: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/rails/routes.rb:242:in `devise_for'
	 31: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/rails/routes.rb:242:in `each'
	 30: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/rails/routes.rb:243:in `block in devise_for'
	 29: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise.rb:346:in `add_mapping'
	 28: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise.rb:346:in `new'
	 27: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/mapping.rb:72:in `initialize'
	 26: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/mapping.rb:162:in `default_used_route'
	 25: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/mapping.rb:95:in `routes'
	 24: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/mapping.rb:78:in `modules'
	 23: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise/mapping.rb:83:in `to'
	 22: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise-4.7.2/lib/devise.rb:316:in `get'
	 21: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
	 20: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/inflector/methods.rb:280:in `constantize'
	 19: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/inflector/methods.rb:280:in `inject'
	 18: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/inflector/methods.rb:280:in `each'
	 17: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/inflector/methods.rb:282:in `block in constantize'
	 16: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/inflector/methods.rb:282:in `const_get'
	 15: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:27:in `require'
	 14: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 13: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 12: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 11: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 10: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	  9: from /Users/danloman/Code/citizenwe-backend/app/models/user.rb:1:in `<main>'
	  8: from /Users/danloman/Code/citizenwe-backend/app/models/user.rb:15:in `<class:User>'
	  7: from /Users/danloman/Code/citizenwe-backend/app/models/user.rb:15:in `include'
	  6: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concern.rb:122:in `append_features'
	  5: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concern.rb:122:in `class_eval'
	  4: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/user.rb:25:in `block in <module:User>'
	  3: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/user.rb:25:in `include'
	  2: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concern.rb:122:in `append_features'
	  1: from /Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concern.rb:122:in `class_eval'
/Users/danloman/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/active_record_support.rb:7:in `block in <module:ActiveRecordSupport>': uninitialized constant DeviseTokenAuth::Concerns::TokensSerialization (NameError)
</details>
</summary>

**Comment by 00dav00** [comment] 2020-08-24 16:58
Hi @namolnad , I've seen this error when the [installation steps](https://github.com/graphql-devise/graphql_devise#installation) are not successfuly completed. Did you get any errors while executing the generator?

**Comment by namolnad** [comment] 2020-08-24 17:24
Thanks for the fast response @00dav00. I did get some errors. A couple of conflicts (which didn't look to be a big deal and was able to keep the original files) and this error which I wasn't able to figure out: `File unchanged! The supplied flag value not found!  app/graphql/my_schema.rb`

**Comment by namolnad** [comment] 2020-08-24 17:28
Not sure if this is a problem, but looks as though the devise_token_auth generator that is run under the hood was passed the wrong arguments. I'm mounting into my schema vs using another route.

I ran: `rails g graphql_devise:install --mount MySchema`
And I just saw this as one of the commands that was run: `rails  generate devise_token_auth:install User graphql_auth`

**Comment by mcelicalderon** [comment] 2020-08-24 17:32
Also try stopping Spring for the unitialized constant error. As for the generator, is you GQL schema in the app called `MySchema`? As in `MySchema < GraphQL::Schema`? Because the generator expects you to already have a GQL schema in your app

**Comment by namolnad** [comment] 2020-08-24 17:39
I was just using `MySchema` as a placeholder for this issue. I do have the appropriately named schema in my app and this was properly inserted into that schema file:
```
  use GraphqlDevise::SchemaPlugin.new(
    query:            Types::QueryType,
    mutation:         Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new('User'),
    ]
  )
```

Unfortunately stopping spring doesn't seem to have helped with the constant error

**Comment by mcelicalderon** [comment] 2020-08-24 17:57
Ok, just make sure you use the right values for the generator as getting this message (`File unchanged! The supplied flag value not found! app/graphql/my_schema.rb`) seems to be because you used MySchema as the schema name. Anyway, make sure both initializer files were generated, one for devise.rb and one for devise_token_auth.rb.

Also, as you are using bootsnap, this might help after `bundle install` and stopping the server. `rm -rf tmp/cache`. Make sure spring is stopped again before running the server.

**Comment by 00dav00** [comment] 2020-08-24 21:09
@namolnad Could you post the backtrace you get when executing the generator please? I think the clue to solve this issue lies there.

**Comment by namolnad** [comment] 2020-08-24 22:17
Sure thing, here's the command i've been running and the output:
```
>> rails g graphql_devise:install --mount CitizenweBackendSchema
Running via Spring preloader in process 61798
    generate  devise:install
       rails  generate devise:install
Running via Spring preloader in process 61800
    conflict  config/initializers/devise.rb
Overwrite /Users/danloman/Code/citizenwe-backend/config/initializers/devise.rb? (enter "h" for help) [Ynaqdhm] n
        skip  config/initializers/devise.rb
   identical  config/locales/devise.en.yml
===============================================================================

Depending on your application's configuration some manual setup may be required:

  1. Ensure you have defined default url options in your environments files. Here
     is an example of default_url_options appropriate for a development environment
     in config/environments/development.rb:

       config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

     In production, :host should be set to the actual host of your application.

     * Required for all applications. *

  2. Ensure you have defined root_url to *something* in your config/routes.rb.
     For example:

       root to: "home#index"

     * Not required for API-only Applications *

  3. Ensure you have flash messages in app/views/layouts/application.html.erb.
     For example:

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

     * Not required for API-only Applications *

  4. You can copy Devise views (for customization) to your app by running:

       rails g devise:views

     * Not required *

===============================================================================
        gsub  app/models/user.rb
        gsub  app/controllers/application_controller.rb
    generate  devise_token_auth:install
       rails  generate devise_token_auth:install User graphql_auth
Running via Spring preloader in process 61826
    conflict  config/initializers/devise_token_auth.rb
Overwrite /Users/danloman/Code/citizenwe-backend/config/initializers/devise_token_auth.rb? (enter "h" for help) [Ynaqdhm] n
        skip  config/initializers/devise_token_auth.rb
     skipped  Concern is already included in the application controller.
        gsub  config/routes.rb
        gsub  config/routes.rb
     skipped  Migration 'devise_token_auth_create_users' already exists
        gsub  config/routes.rb
        gsub  app/models/user.rb
        gsub  app/controllers/application_controller.rb
        gsub  config/initializers/devise_token_auth.rb
File unchanged! The supplied flag value not found!  app/graphql/citizenwe_backend_schema.rb```

**Comment by 00dav00** [comment] 2020-08-25 01:23
As you can see the generator is expecting the file `app/graphql/citizenwe_backend_schema.rb` to exist and contain the schema. Did you check if your project meets this requeriment @namolnad ?

**Comment by namolnad** [comment] 2020-08-25 01:35
@00dav00, it does:
```
>> cat app/graphql/citizenwe_backend_schema.rb
class CitizenweBackendSchema < GraphQL::Schema
  use GraphqlDevise::SchemaPlugin.new(
    query:            Types::QueryType,
    mutation:         Types::MutationType,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new('User'),
    ]
  )

  mutation(Types::MutationType)
  query(Types::QueryType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections
end
```

**Comment by mcelicalderon** [comment] 2020-08-25 04:09
Hey @namolnad, I can confirm I got the same error message on the generator about the file not found and I will look into that. But that doesn't stop the generator to complete installation. Anyway, looks like an autoload problem with Rails, and in a weird place as it happens inside DTA's gem code. You shouldn't have a problem if both initializers are generated properly.

Could you please provide a repo where we can replicate this? I just created [this one](https://github.com/mcelicalderon/test_gem) using your gemfiles and just disabled a couple of gems that I won't have the time to setup. Everything works fine here and created that one from scratch. Even if you can replicate the error on that repo, that'd be awesome.

**Comment by namolnad** [comment] 2020-08-27 02:49
Thanks, will try to create a repo where this can be replicated at some point soon. Needing to keep moving forward on some other things, so may be slightly delayed. I did figure out that the app does boot in a production environment, but not in development/test. Seems closely related to this issue: https://github.com/lynndylanhurley/devise_token_auth/issues/1312

**Comment by mcelicalderon** [comment] 2020-08-27 03:07
Yes, there might be an issue with DTA. And it makes sense, if you need to, probably enabling eager load in development and test environments could fix the problem until we figure this out.

**Comment by louim** [comment] 2020-09-16 16:18
Hey! we encountered the same issue in our App, but luckily it was long after the initial setup, so that helped narrow the problem. I cannot offer a definitive solution, only some hints. In our case, it was caused by an initializer referencing an ActiveRecord Model (in fact it was not even referencing the model directly, only it's stringified name "myModel", but the code was of the related gem was calling `const_get("MyModel")`).

## The setup
- We had an unrelated model (not the User model) called in an initializer
- This seems to cause early loading of the User model (this part is a bit unclear as why to me, probably following the dependency tree)
- Result in `uninitialized constant DeviseTokenAuth::Concerns::TokensSerialization`

## The solution in our case
Switching the initializer to run later fixed the problem.

**Code before:**
```ruby
MyGem.new("UnrelatedModel")
```
Excerpt from the Zeitwerk loading logs:
```
Zeitwerk@rails.main: constant DeviseTokenAuth::Concerns::User loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/user.rb
Zeitwerk@rails.main: constant GraphqlDevise::Concerns::Model loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql_devise-0.13.4/app/models/graphql_devise/concerns/model.rb
Zeitwerk@rails.main: constant DeviseTokenAuth::Concerns::ActiveRecordSupport loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/active_record_support.rb
rails aborted!
NameError: uninitialized constant DeviseTokenAuth::Concerns::TokensSerialization
/Users/louim/work/fx-api/app/models/user.rb:8:in `include'
```

**Code after:**
```ruby
Rails.configuration.to_prepare do
  MyGem.new("UnrelatedModel")
end
```
Excerpt from the Zeitwerk loading logs:
```
Zeitwerk@rails.main: constant DeviseTokenAuth::Concerns::User loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/user.rb
Zeitwerk@rails.main: constant GraphqlDevise::Concerns::Model loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/graphql_devise-0.13.4/app/models/graphql_devise/concerns/model.rb
Zeitwerk@rails.main: constant DeviseTokenAuth::Concerns::TokensSerialization loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/tokens_serialization.rb
Zeitwerk@rails.main: constant DeviseTokenAuth::Concerns::ActiveRecordSupport loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/active_record_support.rb
Zeitwerk@rails.main: constant DeviseTokenAuth::Concerns::UserOmniauthCallbacks loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/models/devise_token_auth/concerns/user_omniauth_callbacks.rb
Zeitwerk@rails.main: constant DeviseTokenAuthEmailValidator loaded from file /Users/louim/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/devise_token_auth-1.1.4/app/validators/devise_token_auth_email_validator.rb
Zeitwerk@rails.main: constant User loaded from file /Users/louim/work/fx-api/app/models/user.rb
```
Like I said above, delaying initialization feels more of a workaround than a proper fix, but I didn't have the time to dig down in this gem (and DTAs) to find the culprit. I hope that it can help people with the same error to narrow their problem.

**Comment by mcelicalderon** [comment] 2020-09-16 21:53
Thanks! Not sure if this helps with @namolnad 's problem, but it makes sense that might have something to do with the Rails lifecycle, looking at initializers or config files is definitely a good place to start looking.

**Comment by mcelicalderon** [comment] 2020-11-19 17:02
Closing this one as no more information was provided and we were never able to reproduce. Please feel free to reopen if you have more information. Thanks!

**Closed by mcelicalderon** 2020-11-19 17:02 UTC
Labels: needs triage
